#define KB_0         0
#define KB_1         1
#define KB_2         2
#define KB_3         3
#define KB_4         4
#define KB_5         5
#define KB_6         6
#define KB_7         7
#define KB_8         8
#define KB_9         9
#define KB_A         10
#define KB_B         11
#define KB_C         12
#define KB_D         13
#define KB_E         14
#define KB_F         15
#define KB_G         16
#define KB_H         17
#define KB_I         18
#define KB_J         19
#define KB_K         20
#define KB_L         21
#define KB_M         22
#define KB_N         23
#define KB_O         24
#define KB_P         25
#define KB_Q         26
#define KB_R         27
#define KB_S         28
#define KB_T         29
#define KB_U         30
#define KB_V         31
#define KB_W         32
#define KB_X         33
#define KB_Y         34
#define KB_Z         35
#define KB_F1        36
#define KB_F2        37
#define KB_F3        38
#define KB_F4        39
#define KB_F5        40
#define KB_F6        41
#define KB_F7        42
#define KB_F8        43
#define KB_F9        44
#define KB_MINUS     45
#define KB_EQUAL     46
#define KB_BACKSPACE 47
#define KB_ENTER     48
#define KB_TILDE     49
#define KB_TAB       50
#define KB_INSERT    51
#define KB_DELETE    52
#define KB_HOME      53
#define KB_END       54
#define KB_PGUP      55
#define KB_PGDOWN    56
#define KB_ESCAPE    57
#define KB_SPACE     58